### ISSUE TITLE
comma-operator

### ISSUE THREAD

**Issue by NikitaDotIvanov64** [Chance20022/Lafore#1]
Ну вот совсем не к месту.
cout << "Enter the number of gallons: ", cin >> ballons;

https://docs.microsoft.com/ru-ru/cpp/cpp/comma-operator?view=vs-2019

[ТЫК](https://github.com/Chance20022/Lafore/blob/master/Chapter%202/Task%201/Task1/Task1.cpp)

**Comment by Chance20022** [comment]
исправил
